baseurl = "https://jabranham.com"
title = "J. Alexander Branham"
copyright = "&copy; 2016-2017 J. Alexander Branham"
languageCode = "en-us"
rssuri = "feed.xml"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
[permalinks]
post = "/blog/:year/:month/:filename"


# Enable comments by entering your Disqus shortname
disqusShortname = "jabranhamblog"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-65548469-1"


[params]
name = "J. Alexander Branham"
  role = "PhD Candidate"
  organization = "University of Texas at Austin"
  avatar = "personal-photo.jpg"
  email = "branham@utexas.edu"
  address = ""
  phone = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:branham@utexas.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/JAlexBranham"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=DuZJkj0AAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/jabranham"

  [[params.social]]
    icon = "rss"
    icon_pack = "fa"
    link = "feed.xml"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#bio"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4

[[menu.main]]
  name = "CV"
  url = "cv/cv.pdf"
  weight = 5


