---
layout: post
title: "Motivation for a Blog"
categories: [why_blog]
tags: [blog]
comments: true
---

I put a decent amount of effort into my setup.
Getting all the programs working just the way I want them to is a little time consuming.
So one day (yesterday, to be precise) I figured it would be a good idea to write down what I've done, just in case I need to do it again someday.
But, in a flash of inspiration, I figure that I can actually put all of this online for the internet to see. 
That way, maybe other grad students, profs, or maybe some industry people might stumble on my blog and find something useful. 

What am I going to blog about? 
Two things: software and my research. 
The software I'm going to blog about is focused on making research easier and more transparent. 
One of the first things I'll write about will be version control.
Most of the software I'll cover will play well with [R](https://cran.r-project.org/index.html), which is the statistical program I use.[^1]
I'll also write posts about how to get things done in R. 

[^1]: They'll also be [free as in beer and free as in speech](http://www.howtogeek.com/howto/31717/what-do-the-phrases-free-speech-vs.-free-beer-really-mean/)

These posts will be written in [rmarkdown](http://rmarkdown.rstudio.com/) and the source files will be available on [Github](https://github.com/jabranham/jabranham.github.io). 
Feel free to suggest a blog topic via the [issues](https://github.com/jabranham/jabranham.github.io/issues) system on github. 
If you do so, please label them using the blog-topic label to help me keep track of everything.
