---
title: Reference Management
---

So as a grad student, I write a lot.
Like, a lot a lot.
And as a part of that, I

# The .bib file
In my last post, I briefly mentioned that you should write your files in plain text.
This applies to your bibliography files as well.
There is a pretty standardized way to format your bibliography files: the ".bib" file.
Your .bib file contains information about each reference you want.
So, for example, if you wanted to cite [Understanding Interaction Models}(http://pan.oxfordjournals.org/content/14/1/63.short) (which everyone should read), your .bib file would contain something like the following: 

    @article{brambor2006,
        title={Understanding Interaction Models: Improving Empirical Analyses},
        author={Brambor, Thomas and Clark, William Roberts and Golder, Matt},
        journal={Political Analysis},
        volume={14},
        number={1},
        pages={63--82},
        year={2006},
    }

The `@` says to begin a new reference.
We then say what kind of thing it is (in this case, an article).
Everything between the curly braces is information about the reference.
So we have information about the title, author, the journal that it's in, etc.
The very first thing ("brambor2006" in this case) is called a bibtex key.
That's how you'll link up the references in your LaTeX (or markdown or whatever) file to the references in your .bib file. 
Lucky for us, we don't actually have to remember how to format all this.
Do google scholar search, and underneath the reference that we want, click "cite" then click "BibTeX" in the window that pops up.
It should then pop up with information similar to what I've posted above. 

# Zotero
[Zotero](https://www.zotero.org/) is a pretty nice bibliography management system.[^zotero]
It can manage your pdf files as well as sync your bibliography across multiple computers.
There is a plug in that allows you to export your bibliography as a .bib file: [Better BibTeX](https://zotplus.github.io/better-bibtex/).
The Better BibTeX plugin can also keep the .bib file updated, so if you add a reference to zotero, it will automatically add it to your .bib file. 

[^zotero]: It's also open source! 

# Auto-completion

# Emacs with RefTeX
